[placeholders]
license = {prompt = "Which license to use?", choices = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause"], default = "MIT", type = "string"}

[template]
include = ["Cargo.toml"]
exclude = ["cliff.toml", ".github/workflows/build.yml"]
ignore = ["target", ".DS_Store"]
